{{- if .Values.frontend.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wiki.frontend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiki.frontend.labels" . | nindent 4 }}
{{- end }}