---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiki.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "wiki.frontend.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      protocol: TCP
      targetPort: http