import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	data: [{ type: "autogenerated", dirName: "data" }],
	language: [{ type: "autogenerated", dirName: "language" }],
	mlops: [{ type: "autogenerated", dirName: "mlops" }],
	platform: [{ type: "autogenerated", dirName: "platform" }],
	protocol: [{ type: "autogenerated", dirName: "protocol" }],
	hardware: [{ type: "autogenerated", dirName: "hardware" }],
	science: [{ type: "autogenerated", dirName: "science" }],
	management: [{ type: "autogenerated", dirName: "management" }],
	comparison: [{ type: "autogenerated", dirName: "comparison" }],
};

export default sidebars;
