import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	entity: [{ type: "autogenerated", dirName: "entity" }],
	concept: [{ type: "autogenerated", dirName: "concept" }],
	operation: [{ type: "autogenerated", dirName: "operation" }],
	specification: [{ type: "autogenerated", dirName: "specification" }],
	troubleshooting: [{ type: "autogenerated", dirName: "troubleshooting" }],
	comparison: [{ type: "autogenerated", dirName: "comparison" }],
};

export default sidebars;
