import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	knowledge: [{ type: "autogenerated", dirName: "knowledge" }],
	language: [{ type: "autogenerated", dirName: "language" }],
	infrastructure: [{ type: "autogenerated", dirName: "infrastructure" }],
	system: [{ type: "autogenerated", dirName: "system" }],
	protocol: [{ type: "autogenerated", dirName: "protocol" }],
	hardware: [{ type: "autogenerated", dirName: "hardware" }],
	science: [{ type: "autogenerated", dirName: "science" }],
	management: [{ type: "autogenerated", dirName: "management" }],
};

export default sidebars;
