name: Build And Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
  workflow_dispatch:

concurrency:
  group: build-and-release
  cancel-in-progress: true

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs:
      imageRepository: ${{ steps.image.outputs.repository }}
      imageTag: ${{ steps.image.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image Repository and Tag
        id: image
        run: |
          IMAGE_REPOSITORY=ghcr.io/hhk7734/wiki
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)

          echo IMAGE_REPOSITORY=$IMAGE_REPOSITORY
          echo IMAGE_TAG=$IMAGE_TAG

          echo "repository=$IMAGE_REPOSITORY" >> $GITHUB_OUTPUT
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hhk7734
          password: ${{ secrets.PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: |
            ${{ steps.image.outputs.repository }}:${{ steps.image.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  gitops:
    name: Update GitOps Repository
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout gitops
        uses: actions/checkout@v4
        with:
          repository: hhk7734/gitops
          ref: main
          token: ${{ secrets.PAT }}
          path: gitops

      - name: Set chart version and copy to gitops
        run: |
          rm -rf gitops/gen/wiki
          mkdir -p gitops/gen
          cp -r deploy/chart gitops/gen/wiki

      - name: Update helm values
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '
              .frontend.image.repository = "${{ needs.build.outputs.imageRepository }}" |
              .frontend.image.tag = "${{ needs.build.outputs.imageTag }}"
            ' gitops/values/wiki/values.yaml

      - name: Commit files
        run: |
          cd gitops
          git add .
          if [ ${{ github.event_name }} = "workflow_dispatch" ] ; then
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          else
            git config --global user.name "${{ github.event.head_commit.author.name }}"
            git config --global user.email "${{ github.event.head_commit.author.email }}"
          fi
          git commit -m "feat(wiki): bump to ${{ needs.build.outputs.imageTag }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: hhk7734/gitops
          branch: main
          github_token: ${{ secrets.PAT }}
          directory: gitops
