name: Build And Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
  workflow_dispatch:

concurrency:
  group: build-and-release
  cancel-in-progress: true

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v3.2.0

      - name: Build and Release
        env:
          GIT_USER: hhk7734
          GIT_PASS: ${{ secrets.PAT }}
        run: |
          if [ ${{ github.event_name }} = "workflow_dispatch" ] ; then
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          else
            git config --global user.name "${{ github.event.head_commit.author.name }}"
            git config --global user.email "${{ github.event.head_commit.author.email }}"
          fi

          npm install --omit=dev
          npm run deploy
