name: wiki.loliot.net CD pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: wiki-cd
  cancel-in-progress: true

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs:
      imageRepository: ${{ steps.image.outputs.repository }}
      imageTag: ${{ steps.image.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image Repository and Tag
        id: image
        run: |
          IMAGE_REPOSITORY=ghcr.io/${{ github.repository_owner }}/wiki
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-8)
          # IMAGE_TAG=${{ github.ref_name }}

          echo IMAGE_REPOSITORY=$IMAGE_REPOSITORY
          echo IMAGE_TAG=$IMAGE_TAG

          echo "repository=$IMAGE_REPOSITORY" >> $GITHUB_OUTPUT
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: |
            ${{ steps.image.outputs.repository }}:${{ steps.image.outputs.tag }}

  argo-cd:
    name: Update ArgoCD Repository
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout argo-cd
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/argo-cd
          ref: main
          token: ${{ secrets.PAT }}
          path: argo-cd

      - name: Update helm values
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '
              .frontend.image.repository = "${{ needs.build.outputs.imageRepository }}" |
              .frontend.image.tag = "${{ needs.build.outputs.imageTag }}"
            ' argo-cd/wiki/cd/prod-values.yaml

      - name: Commit files
        run: |
          cd argo-cd
          git config --global user.name "${{ github.event.head_commit.author.name }}"
          git config --global user.email "${{ github.event.head_commit.author.email }}"
          git commit -am "feat(wiki): set tag to ${{ needs.build.outputs.imageTag }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ github.repository_owner }}/argo-cd
          github_token: ${{ secrets.PAT }}
          branch: main
          directory: argo-cd
