name: wiki.loliot.net CD pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: wiki-cd
  cancel-in-progress: true

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set TAG
        id: tag
        run: |
          TAG=$(echo ${{ github.sha }} | cut -c1-8)
          echo TAG=$TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/wiki:${{ steps.tag.outputs.tag }}

  argocd:
    name: Update ArgoCD Repository
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout argocd
        uses: actions/checkout@v4
        with:
          repository: hhk7734/argocd
          ref: main
          token: ${{ secrets.PAT }}
          path: argocd

      - name: Update helm values
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '
              .frontend.image.repository = "ghcr.io/${{ github.repository_owner }}/wiki" |
              .frontend.image.tag = "${{ needs.build.outputs.imageTag }}"
            ' argocd/wiki/cd/prod-values.yaml

      - name: Commit files
        run: |
          cd argocd
          git config --global user.name "${{ github.event.head_commit.author.name }}"
          git config --global user.email "${{ github.event.head_commit.author.email }}"
          git commit -am "feat(wiki): set tag to ${{ needs.build.outputs.imageTag }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: hhk7734/argocd
          github_token: ${{ secrets.PAT }}
          branch: main
          directory: argocd
